// Reference data for the UI before live indexing is wired.
// IMPORTANT: these values are sample/demo values, not a claim about current protocol APY/TVL.
// The reference program IDs are syntactically valid public keys but are not represented as deployed Dnipro programs.

export const MOCK_ADAPTERS = [
  {
    id: 'kamino',
    programId: 'GENyHjfFyapa8AA8HaxLvZE9eZ3uMFca18d26RJJ9DxB',
    programIdStatus: 'reference' as const,
    integrationStatus: 'Reference' as const,
    dataMode: 'Sample' as const,
    name: 'Kamino USDC',
    protocol: 'kamino',
    description: 'Reference lending adapter for a Kamino USDC strategy. Complete and verify the underlying protocol CPI before marking this route live.',
    underlyingMint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    underlyingSymbol: 'USDC',
    category: 0,
    categoryLabel: 'Lending',
    apyBps: 820,
    apyPercent: '8.20%',
    tvlFormatted: '$47.3M',
    tvlRaw: 47_300_000,
    isActive: false,
    depositsPaused: true,
    minDeposit: 1_000_000,
    maxDeposit: 0,
    riskScore: 20,
    riskLabel: 'Low' as const,
    withdrawalDelay: null,
    website: 'https://kamino.finance',
    docs: 'https://docs.kamino.finance',
    auditUrl: 'https://docs.kamino.finance/security',
    shareSymbol: 'kUSDC',
    exchangeRateBps: 10_412,
    icon: 'K',
  },
  {
    id: 'marginfi',
    programId: '7s7FUYn9h5gtjaUpMjDTuaAEcNH9Zm2g6JYaJ9gY76SP',
    programIdStatus: 'reference' as const,
    integrationStatus: 'Reference' as const,
    dataMode: 'Sample' as const,
    name: 'MarginFi USDC',
    protocol: 'marginfi',
    description: 'Reference lending adapter for a MarginFi USDC route. Protocol-specific CPI and deployed-address verification are required before production use.',
    underlyingMint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    underlyingSymbol: 'USDC',
    category: 0,
    categoryLabel: 'Lending',
    apyBps: 750,
    apyPercent: '7.50%',
    tvlFormatted: '$31.8M',
    tvlRaw: 31_800_000,
    isActive: false,
    depositsPaused: true,
    minDeposit: 1_000_000,
    maxDeposit: 0,
    riskScore: 25,
    riskLabel: 'Low' as const,
    withdrawalDelay: null,
    website: 'https://app.marginfi.com',
    docs: 'https://docs.marginfi.com',
    auditUrl: 'https://docs.marginfi.com/security',
    shareSymbol: 'mfUSDC',
    exchangeRateBps: 10_380,
    icon: 'M',
  },
  {
    id: 'jupiter',
    programId: 'Eh9e2Q55pKimA7TA5z6qoGi92xXqqYEKagdv1pvwCfLi',
    programIdStatus: 'reference' as const,
    integrationStatus: 'Reference' as const,
    dataMode: 'Sample' as const,
    name: 'Jupiter LP (JLP)',
    protocol: 'jupiter',
    description: 'Reference liquidity adapter for a Jupiter JLP-style route. Live execution should use verified protocol accounts and current pool state.',
    underlyingMint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    underlyingSymbol: 'USDC',
    category: 1,
    categoryLabel: 'Liquidity',
    apyBps: 1840,
    apyPercent: '18.40%',
    tvlFormatted: '$892.1M',
    tvlRaw: 892_100_000,
    isActive: false,
    depositsPaused: true,
    minDeposit: 1_000_000,
    maxDeposit: 0,
    riskScore: 40,
    riskLabel: 'Medium' as const,
    withdrawalDelay: null,
    website: 'https://jup.ag/perps',
    docs: 'https://station.jup.ag/docs/perpetual-exchange/jlp',
    auditUrl: 'https://station.jup.ag/docs/security',
    shareSymbol: 'JLP',
    exchangeRateBps: 11_840,
    icon: 'J',
  },
  {
    id: 'maple',
    programId: 'Ht1uo1tiXUjPouaNmDxqNpGN5K7jNi4jGJq6crZPrPcv',
    programIdStatus: 'reference' as const,
    integrationStatus: 'Reference' as const,
    dataMode: 'Sample' as const,
    name: 'Maple / Syrup',
    protocol: 'maple',
    description: 'Reference adapter for a credit/RWA yield route. Any live build must verify chain support, token contracts, and withdrawal semantics first.',
    underlyingMint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    underlyingSymbol: 'USDC',
    category: 2,
    categoryLabel: 'Real World Asset',
    apyBps: 1250,
    apyPercent: '12.50%',
    tvlFormatted: '$24.6M',
    tvlRaw: 24_600_000,
    isActive: false,
    depositsPaused: true,
    minDeposit: 100_000_000,
    maxDeposit: 0,
    riskScore: 55,
    riskLabel: 'Medium' as const,
    withdrawalDelay: '7 days',
    website: 'https://maple.finance',
    docs: 'https://maplefinance.gitbook.io',
    auditUrl: 'https://maple.finance/security',
    shareSymbol: 'syrupUSDC',
    exchangeRateBps: 10_620,
    icon: 'S',
  },
  {
    id: 'drift',
    programId: '8ZEWPwXBjTG3DsP2sJLYpgf5iTgGay4C8YJoc5mb4YP8',
    programIdStatus: 'reference' as const,
    integrationStatus: 'Reference' as const,
    dataMode: 'Sample' as const,
    name: 'Drift Insurance Fund',
    protocol: 'drift',
    description: 'Reference insurance-fund adapter. Live integration must preserve Drift-specific staking and cooldown rules and use verified program accounts.',
    underlyingMint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    underlyingSymbol: 'USDC',
    category: 3,
    categoryLabel: 'Insurance',
    apyBps: 960,
    apyPercent: '9.60%',
    tvlFormatted: '$8.9M',
    tvlRaw: 8_900_000,
    isActive: false,
    depositsPaused: true,
    minDeposit: 1_000_000,
    maxDeposit: 0,
    riskScore: 45,
    riskLabel: 'Medium' as const,
    withdrawalDelay: '14 days',
    website: 'https://drift.trade',
    docs: 'https://docs.drift.trade/insurance-fund',
    auditUrl: 'https://docs.drift.trade/security',
    shareSymbol: 'IF-USDC',
    exchangeRateBps: 10_480,
    icon: 'D',
  },
];

// Sample portfolio used only to demonstrate the dashboard layout.
export const MOCK_POSITIONS = [
  {
    adapterId: 'kamino',
    depositedAmount: 5_000_000_000,
    shares: 4_802_110_000,
    currentValue: 5_206_500_000,
    pnl: 206_500_000,
    pnlPercent: '+4.13%',
    openedAt: 1710000000,
    lastUpdatedAt: Date.now() / 1000,
  },
  {
    adapterId: 'jupiter',
    depositedAmount: 2_000_000_000,
    shares: 169_169_000,
    currentValue: 2_368_000_000,
    pnl: 368_000_000,
    pnlPercent: '+18.40%',
    openedAt: 1705000000,
    lastUpdatedAt: Date.now() / 1000,
  },
];

export const PORTFOLIO_SUMMARY = {
  totalDeposited: 7_000_000_000,
  totalValue: 7_574_500_000,
  totalPnl: 574_500_000,
  pnlPercent: '+8.21%',
};

// Deterministic sample history to avoid presenting a random chart as historical market data.
export function generateApyHistory(baseBps: number, days = 30) {
  return Array.from({ length: days }, (_, i) => ({
    date: new Date(Date.now() - (days - i) * 86400000).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
    apy: (baseBps + Math.sin(i * 0.4) * 50) / 100,
  }));
}
